---
title: "MCBoost - Health Survey Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MCBoost - Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(purrr)
library(PracTools)
library(randomForest)
library(formattable)
library(mlr3)
library(mlr3learners)
library(mcboost)
```

## Data

```{r}
data(nhis.large)
```

```{r}
predictors <- c("age.grp", "parents", "educ", "inc.grp", "doing.lw", "limited", "sex", "hisp", "race")

nhis <- nhis.large %>%
  mutate_at(predictors, as_factor) %>%
  mutate_at(predictors, fct_explicit_na) %>%
  drop_na(notcov) %>%
  select(all_of(predictors), notcov, svywt, ID)

nhis$notcov <- factor(ifelse(nhis$notcov == 1, "notcov", "cov"))

nhis_enc <- data.frame(model.matrix(notcov ~ ., data = nhis)[,-1])
nhis_enc$notcov <- nhis$notcov
nhis_enc$sex <- nhis$sex
nhis_enc$hisp <- nhis$hisp
nhis_enc$race <- nhis$race
nhis_enc$inv_wt <- (1 / nhis$svywt)
```

```{r}
test <- nhis_enc %>% slice_sample(prop = 0.3, weight_by = inv_wt)

nontest_g <- nhis_enc %>% anti_join(test, by = "ID")

train_g <- nontest_g %>% slice_sample(prop = 0.6)

post <- nontest_g %>% anti_join(train_g, by = "ID") %>% select(-ID, -svywt, -inv_wt, -c(sex:race))

train <- train_g %>% select(-ID, -svywt, -inv_wt, -c(sex:race), -c(sex2:race3))
```

```{r}
train_g %>% summarise_at(vars(sex2:race3), mean)
```

```{r}
post %>% summarise_at(vars(sex2:race3), mean)
```

```{r}
test %>% summarise_at(vars(sex2:race3), mean)
```

## Initial model

```{r}
set.seed(23)
rf <- randomForest(notcov ~ ., 
                   data = train)
```

```{r}
logit <- glm(notcov ~ ., 
             family = "binomial",
             data = train)
```

## MCBoost

```{r}
init_rf = function(data) {
  predict(rf, data, type = "prob")[, 2]
}

init_logit = function(data) {
  predict(logit, data, type = "response")
}
```

```{r}
d1 <- select(post, -notcov)
d2 <- select(d1, -c(sex2:race3))
l <- 1 - one_hot(post$notcov)
```

```{r}
ridge = LearnerResidualFitter$new(lrn("regr.glmnet", alpha = 0, lambda = 2 / nrow(post)))

net = LearnerResidualFitter$new(lrn("regr.glmnet", alpha = 0.5, lambda = 2 / nrow(post)))

pops = SubpopFitter$new(list("sex2", "hisp2", "hisp3", "hisp4", "race2", "race3"))
```

```{r}
mc1 = MCBoost$new(init_predictor = init_rf, 
                 subpop_fitter = ridge,
                 multiplicative = TRUE,
                 partition = TRUE,
                 max_iter = 15)
mc1$multicalibrate(d2, l)

mc2 = MCBoost$new(init_predictor = init_rf, 
                 subpop_fitter = pops,
                 partition = TRUE,
                 max_iter = 15)
mc2$multicalibrate(d1, l)

mc3 = MCBoost$new(init_predictor = init_logit, 
                 subpop_fitter = net,
                 multiplicative = TRUE,
                 partition = TRUE,
                 max_iter = 15)
mc3$multicalibrate(d2, l)

mc4 = MCBoost$new(init_predictor = init_logit, 
                 subpop_fitter = pops,
                 partition = TRUE,
                 max_iter = 15)
mc4$multicalibrate(d1, l)
```

## Evaluate

```{r}
test$rf <- predict(rf, newdata = test, type = "prob")[, 2]
test$logit <- predict(logit, newdata = test, type = "response")
test$mc1 <- mc1$predict_probs(test)
test$mc2 <- mc2$predict_probs(test)
test$mc3 <- mc3$predict_probs(test)
test$mc4 <- mc4$predict_probs(test)

test$c_rf <- round(test$rf)
test$c_logit <- round(test$logit)
test$c_mc1 <- round(test$mc1)
test$c_mc2 <- round(test$mc2)
test$c_mc3 <- round(test$mc3)
test$c_mc4 <- round(test$mc4)
test$label <- 1 - one_hot(test$notcov)
```

```{r}
mean(test$c_rf == test$label)
mean(test$c_mc1 == test$label)
mean(test$c_mc2 == test$label)

mean(test$c_logit == test$label)
mean(test$c_mc3 == test$label)
mean(test$c_mc4 == test$label)
```

```{r}
test <- test %>% 
  mutate(sex_hisp = group_indices(., sex, hisp),
         sex_race = group_indices(., sex, race),
         hisp_race = group_indices(., hisp, race))

grouping_vars <- c("sex", "hisp", "race", "sex_hisp", "sex_race", "hisp_race")

eval <- map(grouping_vars, group_by_at, .tbl = test) %>%
  map(summarise,
      'accuracy_rf' = mean(c_rf == label),
      'accuracy_mc1' = mean(c_mc1 == label),
      'accuracy_mc2' = mean(c_mc2 == label),
      'accuracy_logit' = mean(c_logit == label),
      'accuracy_mc3' = mean(c_mc3 == label),
      'accuracy_mc4' = mean(c_mc4 == label),
      'bias_rf' = abs(mean(rf) - mean(label))*100,
      'bias_mc1' = abs(mean(mc1) - mean(label))*100,
      'bias_mc2' = abs(mean(mc2) - mean(label))*100,
      'bias_logit' = abs(mean(logit) - mean(label))*100,
      'bias_mc3' = abs(mean(mc3) - mean(label))*100,
      'bias_mc4' = abs(mean(mc4) - mean(label))*100,
      'size' = n()) %>%
  bind_rows()
```

```{r}
eval %>%
  arrange(desc(size)) %>%
  select(size, accuracy_rf:accuracy_mc4) %>%
  round(., digits = 3) %>%
  formattable(., lapply(1:nrow(eval), function(row) {
  area(row, col = 2:7) ~ color_tile("transparent", "lightgreen")
    }))
```

```{r}
eval %>%
  arrange(desc(size)) %>%
  select(size, bias_rf:bias_mc4) %>%
  round(., digits = 3) %>%
  formattable(., lapply(1:nrow(eval), function(row) {
  area(row, col = 2:7) ~ color_tile("lightgreen", "transparent")
    }))
```
